name: extro
description: A Flutter customer application following clean architecture.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^9.2.0
  injectable: ^2.7.1+2
  
  # Immutable Models
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.1
  
  # Network
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  
  # Functional Programming
  dartz: ^0.10.1
  
  # Code Generation
  intl: ^0.20.2
  
  # Authentication
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^7.0.1

  # Routing
  auto_route: ^10.3.0
  shared_preferences: ^2.2.0

  # Local Database
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Routing codegen
  auto_route_generator: ^10.2.6
  # Code Generation
  build_runner: ^2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  injectable_generator: ^2.8.1
  # Database code generation
  drift_dev: ^2.14.0
  # Testing
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/svgs/
