name: extro
description: A Flutter customer application following clean architecture.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Immutable Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Network
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  
  # Functional Programming
  dartz: ^0.10.1
  
  # Code Generation
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/svgs/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
