name: iOS CI Build

on:
  push:
    branches: [ develop ]

jobs:
  analyze:
    name: iOS Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.6"
          channel: 'stable'
          cache: true
          cache-key: "flutter-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}"
          cache-path: "${{ runner.tool_cache }}/flutter"

      - name: Fetch dependencies
        run: flutter pub get

      - name: Generate necessary code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build iOS (no codesign)
        run: flutter build ios --no-codesign
